// Generated by CoffeeScript 1.9.2
(function() {
  var uqamValidator;

  uqamValidator = require('./uqam-validator');

  console.log('Code postal valide H2L 2C4 : ', uqamValidator.isCodePostalCanadien('H2L 2C4'));

  console.log('Code postal invalide H2L 2C4 : ', !uqamValidator.isCodePostalCanadien('H2L 2C'));

  console.log('Domaine UQAM : ', uqamValidator.isDomaineUqam('unsite.uqam.ca'));

  console.log('Pas domaine UQAM : ', !uqamValidator.isDomaineUqam('www.perdu.com'));

  console.log('Code permanent : ', uqamValidator.isCodePermanent('CONQ01010106'));

  console.log('Pas code permanent : ', !uqamValidator.isCodePermanent('GJ456789sdsa'));

  console.log('Bon nip : ', uqamValidator.isNip('12345'));

  console.log('Mauvais nip : ', !uqamValidator.isNip('12547845'));

  console.log('Bon phone : ', uqamValidator.isTelephoneNordAmericain('(514)987-3000'));

  console.log('Mauvais phone : ', !uqamValidator.isTelephoneNordAmericain('12547845'));

}).call(this);

//# sourceMappingURL=pseudoTest.js.map
